### ISSUE TITLE
Export component not working unless "Add to Palette" checked

### ISSUE THREAD

**Issue by hellocld** [praxis-live/support#101]
Whenever I try to export a custom component to save the .pxg inside the project I'm working with, it doesn't save the .pxg unless I have "Add to Palette" checked in the export window.

**Comment by neilcsmith-net** [comment]
Interesting! Thanks for the report. I'm just finishing some things off for the 4.3 release.  I'll take a look.

**Comment by neilcsmith-net** [comment]
OK, I'd managed to stupidly set it up so that it was swallowing a NullPointerException. Pushed a quick fix for the next release to https://github.com/praxis-live/praxis-live/commits/nb11  More work to do on export in a future release when I'll probably review this fix a bit more.

Unfortunately the only workaround for 4.2 is going to be removing it from the palette after you've exported - `Remove` in the pop-up menu on it in the Palette tab if you haven't found it yet.

**Comment by hellocld** [comment]
Ahhh, gotcha, that makes sense. No worries, thanks for looking into it!

**Comment by neilcsmith-net** [comment]
Fixed in 4.3. Thanks for reporting.
