### ISSUE TITLE
Let's make a PraxisLive AppImage

### ISSUE THREAD

**Issue by probonopd** [praxis-live/support#110]
Providing an [AppImage](http://appimage.org/) would have, among others, these advantages:
- Applications packaged as an AppImage can run on many distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others)
- One app = one file = super simple for users: just download one AppImage file, [make it executable](http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80), and run
- No unpacking or installation necessary
- No root needed
- No system libraries changed
- Works out of the box, no installation of runtimes needed
- Optional desktop integration with `appimaged`
- Optional binary delta updates, e.g., for continuous builds (only download the binary diff) using AppImageUpdate
- Can optionally GPG2-sign your AppImages (inside the file)
- Works on Live ISOs
- Can use the same AppImages when dual-booting multiple distributions
- Can be listed in the [AppImageHub](https://appimage.github.io/) central directory of available AppImages
- Can double as a self-extracting compressed archive with the `--appimage-extract` parameter
- No repositories needed. Suitable/optimized for air-gapped (offline) machines
- Decentralized

[Here is an overview](https://appimage.github.io/apps) of projects that are already distributing upstream-provided, official AppImages.

If you have questions, AppImage developers are on #AppImage on irc.freenode.net.

**Comment by probonopd** [comment]
As discussed at #lgw19, there is a Java version that allows one to just ship the subset of JRE that is needed fo run a particular application. Do you know how to create this subset @neilcsmith-net?

**Comment by neilcsmith-net** [comment]
Thanks @probonopd and good to talk to you about this at LGM.  PraxisLIVE itself needs a full JDK, so there's not really anything to remove in a subset, although from v5 we should be able to support this for exported standalone project (in an automated way, could already be done manually).

The key thing I need to look at is ensuring the two binaries inside the installation `bin/praxis` and `bin/praxislive` can be run from inside and outside the AppImage (I'll check out the ImageMagick AppImage you suggested)

**Comment by probonopd** [comment]
Specifically, check https://gitlab.com/inkscape/inkscape/blob/883c7bc26f6268e1a121b796c3af76b8bce315e8/packaging/appimage/AppRun#L8-29

**Comment by neilcsmith-net** [comment]
Thanks!

**Comment by probonopd** [comment]
On a deb-based system, run

```
wget -c "https://github.com/AppImage/pkg2appimage/raw/master/pkg2appimage"
bash -ex pkg2appimage PraxisLIVE
```

The resulting `PraxisLIVE-4.3.0.glibc2.15-x86_64.AppImage` should be able to run on other distributions, too.

The above wrapper script is not yet included.

The yml file that controls the AppImage generation is at
https://github.com/AppImage/pkg2appimage/blob/master/recipes/PraxisLIVE.yml
and probably needs some fine-tuning:

* Instead of downloading a zip, it should use the data from this repository locally
* A proper icon is needed
* The above wrapper script needs to be included as a custom `AppRun`

**Comment by probonopd** [comment]
Please thoroughly test it and report back any issues. Thanks.

**Comment by neilcsmith-net** [comment]
I'll take a look soon, thanks.

The icons are currently at https://github.com/praxis-live/distribution/tree/master/common  The icons for Windows and macOS are now in the main repo - need to add the png there too, and include in probably include all in `etc` inside the zip.

The desktop file from the current `.deb` is here - key things would be Categories is wrong, and StartupWMClass is necessary.

```
[Desktop Entry]
Name=PraxisLIVE
Comment=PraxisLIVE
Exec=/usr/bin/praxislive
Icon=praxislive.png
Categories=Development;Java;
Terminal=false
Type=Application
StartupWMClass=PraxisLIVE
```

I would probably switch to using OpenJDK 11 from AdoptOpenJDK.  https://adoptopenjdk.net/  Had a few issues with Debian packaged OpenJDK recently.

I'm definitely interested in improving support for creating standalone applications, including potentially the ability to export AppImage.  At the moment, I'm looking at how to use PraxisLIVE projects to do this so that IDE tasks can be extended and edited by users.

The other use of the CLI `praxis` command incidentally is running projects outside of the IDE - `praxis <projectDir>`

**Comment by probonopd** [comment]
> I would probably switch to using OpenJDK 11 from AdoptOpenJDK. https://adoptopenjdk.net/ 

I did not know about this. Cool! It looks like especially the OpenJ9 is optimized for performance, and for desktop apps we should use `java -jar -Xquickstart ...`.

I was even able to package a subset of Java for a small Java AppImage, see https://github.com/AppImage/AppImageKit/wiki/Bundling-Java-apps#bundling-a-subset-of-java-using-adoptopenjdk-openj9-jlink.

**Comment by neilcsmith-net** [comment]
> I did not know about this.

There are lots of other vendors for OpenJDK now that Oracle have changed OpenJDK to a 6-month release model and no longer provide a free long term support JDK.  Adopt is my favoured as they're a community supported effort, although Azul OpenJDK 8 is used in Windows and macOS versions of PraxisLIVE currently.

> It looks like especially the OpenJ9 is optimized for performance, and for desktop apps we should use `java -jar -Xquickstart ...`.

Possibly!  Depends on your definition and requirements for performance. :smile:  I've been doing a lot of testing with both OpenJ9 and HotSpot.

> I was even able to package a subset of Java for a small Java AppImage, see https://github.com/AppImage/AppImageKit/wiki/Bundling-Java-apps#bundling-a-subset-of-java-using-adoptopenjdk-openj9-jlink.

Looks good, although I would change any reference to Java 9/10 to 11 now they're no longer supported.  I'm also not sure how different the JavaFX / JavaPackager aspect might need to be with 11.

**Comment by probonopd** [comment]
Updated the yml file to use OpenJDK11U-jdk_x64_linux_openj9_11.0.3_7_openj9-0.14.3.tar.gz and to use the correct icon. Please have a try!

**Comment by probonopd** [comment]
Is that the version of the JDK you wanted? It'd probably be easy to switch to another one.

**Comment by neilcsmith-net** [comment]
Thanks!  Will take another look soon.  For v5 an AppImage will probably be the default distribution mechanism.  I may try an experimental option for v4.4 too.

I'm not sure yet whether to default to OpenJ9 - some pros, but also slightly less performant.

I also need to make sure that `/usr/bin/praxis` can be called both internally from the IDE, and externally by the user on the CLI.

**Comment by neilcsmith-net** [comment]
Only a year later, sorry @probonopd , but I'm picking this up again as we get close to full v5 release. Just uploaded a test appimage for the beta1 release - https://github.com/praxis-live/praxis-live/releases/tag/v5.0.0-beta-1  Unfortunately, no longer the smaller bundle, but comparable.  I need to see if we can get the bundle size down a little with JLink anyway, although that might not be worth the trouble.

I'm currently building manually with an AppDir based on the earlier .deb structure, then passing through `appimagetool`. Have to look at whether to integrate like that into the ant build (like Windows and macOS are), or base it on `pkg2appimage` approach you shared, look at the GitHub-based CI, etc.  Any pros / cons to be aware of?

Structure is very simple, and a symlinked `AppRun` works for the IDE, but took the link you shared as inspiration so that PraxisCORE can still be run externally. Internal packaging of that changed significantly from v4.

```bash
#!/bin/bash

HERE="$(dirname "$(readlink -f "${0}")")"

if [ "praxis" = "$1" ] ; then
  if [ -z "$JAVA_HOME" ] ; then
    export JAVA_HOME="$HERE/usr/lib/praxislive/jdk/"
  fi
  MAIN="$HERE/usr/bin/praxis" ; shift
else
  MAIN="$HERE/usr/bin/praxislive"
fi

exec "${MAIN}" "$@"
```

Thanks! :smile:

**Comment by probonopd** [comment]
Published :-)

https://appimage.github.io/PraxisLIVE/

Maybe you'd like to consider adding a nice screenshot using AppStream metainfo: https://docs.appimage.org/packaging-guide/optional/appstream.html

Regarding jlink, I had some success with https://github.com/AppImage/AppImageKit/wiki/Bundling-Java-apps#bundling-a-subset-of-java-using-adoptopenjdk-openj9-jlink (when I tried bundling another application).

Since your current way of making AppImages works, I don't think you would gain much by switching to `pkg2appimage`.

**Comment by neilcsmith-net** [comment]
Thanks!  I'll take a look at the metainfo stuff as I finish off final release.  beta2 will have a fix for some occasional issues with NetBeans' caching, which was storing absolute paths due to the odd way we package PraxisCORE in there - a bit of code that doesn't like the AppImage's mount point moving around - should now be sorted.

Using JLink isn't the problem, it's the fact that we need a full JDK so I'm not sure if there's much we can exclude.  If we only drop a few MB it's not worth the hassle.

OK, I'll keep with existing mechanism but attempt to build into the Ant scripts like we already have for Windows and macOS.  Any examples you're aware of for building an AppDir and executing `appimagetool` via Ant?

**Comment by probonopd** [comment]
Unfortunately I have not the slightest clue about Ant...

**Comment by neilcsmith-net** [comment]
Thanks!  No problem.  I'd keep it that way too .. :smile: .. but for various reasons we're stuck using it for the IDE for time being.
