### ISSUE TITLE
Project no longer builds

### ISSUE THREAD

**Issue by maxdee** [praxis-live/support#18]
Encountering a bug for the second time. I think it has something to do with deleting a hub. Here is the log and I will email you the project.
[log_project_not_opening.txt](https://github.com/praxis-live/support/files/148497/log_project_not_opening.txt)

**Comment by maxdee** [comment]
Ok I figured it out. I had deleted the midi hub called `xsessionpro.pxr` through the project tab and the `VJuserZero.pxp` did not reflect this change. I manually deleted `include [file "xsessionpro.pxr"]` and `include [file "config/xsessionpro_autostart"]` from the `.pxp` file and now it builds fine.

**Comment by neilcsmith-net** [comment]
Thanks for the report. I think this is due to the issue I've just opened #19  It's a long standing problem and needs fixing.  The workaround is included in that issue report - you can change the `.pxp` file data from inside the application.

Once #19 is fixed, please reopen this if it proves to be more than just that issue.

btw - need to work on your terminology :smile: You're deleting a _root_ not a _hub_.

**Comment by maxdee** [comment]
Wicked. Is there newer releases to test? Would be glad to.
