### ISSUE TITLE
Webcam not recognized

### ISSUE THREAD

**Issue by Gabirell** [praxis-live/support#39]
Hello! First of all, congratulations for the software. I've been playing with it today and its amazing!!!

So, I was playing with the video input example (04) and I receive this error at compiling:<html><b>video.pxr</b> : Couldn't set property /video/capture.device
I've tried all input channels with no sucess.
I'm on Macbook pro OSX Yosemite with an internal webcam (isight) and an external one.
None is recognized.
Thanks in advance!

**Comment by neilcsmith-net** [comment]
Thanks! Glad you're enjoying it 😄 

Firstly. the obvious question, have you installed the GStreamer framework?  It's linked to on the start page and on the GitHub releases page.

Assuming you have, I think the default capture pipelines for OSX need to be updated.  You can override with custom GStreamer elements and pipelines in the `device` property of the capture component.  See the documentation at http://praxis-live.readthedocs.io/en/latest/components-video/

Firstly, ignore the dropdown on the device property and set it to `autovideosrc` If that works then try `avfvideosrc` as that's probably what the pipelines need to be updated to.  If it doesn't work then try `videotestsrc`.  If the test source doesn't work then GStreamer linking isn't working - open `View | IDE log` and attach the log (you should be able to save the output as a file by right-clicking?)

Note that `Tools / Options / Video / GStreamer` is under the `praxis_live` menu on OSX - called preferences IIRC.

Thanks and best wishes, Neil

**Comment by Gabirell** [comment]
Wow, that was a fast reply! thanks! 
I must confess I can't stop playing with your software... :)
Yes, it was absolutely as you guessed: I thought I had GStramer properly installed already. I didn't. So I've installed the GStreamer and the external usb camera was immediately recognized... But... not the isight. I've done partially what you suggested, (changed the preferences input "Device 1 qtkitvideosrc device-index=0" to "autovideosrc") maybe I'm not so used with the workflow yet... first, when I switch via global prefs the cam route to isight it gets really, really slow (the external one its absolutely normal).. the test I'm working now is to make a clean switch between cameras: but when I switch between cam1 and cam2 both turn black. Even with "global" preferences changed, I experience some problems: Firstly it recognizes cam1 (external) but if I switch (via video input properties in the patch itself) to cam2 (isight) it remains black and when I go back again to cam1 it doesn't "start" again and remains black too. Maybe I need to re-start it on programming again? am I loosing something? Thanks again, Neil
best wishes for you too

**Comment by neilcsmith-net** [comment]
Well, that's good to know - glad you're having fun with it! 😄 

Firstly, please consider the Google Groups for general support questions (or I'm open to suggestions for a better alternative). The issues queue is awkward for general support.

http://groups.google.com/d/forum/praxis-live

With regards to your questions.  Firstly, if `autovideosrc` is working, try changing the pipelines to use `avfvideosrc` rather than `qtkitvideosrc` and see if that works.  The automatic source doesn't support device index so will just use the first camera it can find.

Anytime you switch any of the properties in `video:capture` you need to restart it - button in the dialog, or option in the popup menu.

It's possible the isight has a higher resolution or framerate?  Try setting the width, height and framerate properties in the `video:capture` component - by default it will use the highest possible.  Also make sure you're using the OpenGL renderer.  The current webcam example uses software rendering, which I'll probably update soon, but make sure to disconnect the bars component if you are testing as that will force it back to software rendering.

Hope that helps!
