### ISSUE TITLE
Installer cannot find JDK 

### ISSUE THREAD

**Issue by aidinzolghadr** [praxis-live/support#60]
Hi,

I have installed JDK versions 9, 8 and 7 and installer cannot find either of them. I tried give it's location via -javahome switch but didin't help (I gave the root directory of JDK, was not sure).

In command line when I run "java -version" it outputs 9. I ran the Java configuration utility and unticked the 9 version and it just has version 7 there, also didn't help.

I have Win 7 64-bit and installed 32-bit versions of JDK.

It's strange, it did run fine on another machine with similar setup.

Thanks

**Comment by neilcsmith-net** [comment]
Thanks for the report and sorry to hear you're having trouble.  Not sure if this article provides any useful additional information - http://wiki.netbeans.org/FaqInstallJavahome  Praxis LIVE currently uses the installer from NetBeans.  A priority for 2018 is to switch to another installer (probably InnoSetup) and bundle an included JDK.

Note that due to other NetBeans IDE issues, Praxis LIVE requires Java 8 and will not run on Java 9 at present.

I recommend always installing a 64-bit JDK unless you specifically need a 32-bit one for something else.  I would uninstall all the JDK's and install a 64-bit Java 8 JDK from scratch.  Praxis LIVE is generally tested with 64-bit OpenJDK 8 from Azul - https://www.azul.com/downloads/zulu/zulu-windows/  This is probably what will be bundled.

If you still can't get the installer to work, you can also use the .zip download as a workaround - note you have to launch `bin/praxis_live.exe`

Hope that helps!

**Comment by aidinzolghadr** [comment]
​Hi,

Thanks for the quick reply. Should I install ​client or server OepnJDK?
There are two versions on the Azul's site that you linked.

Also I like to install the official JDK version​ since it may interfere
with other programs, not sure about this.

And zip file is very small, how it would work as it does not bundle the JDK.

Thanks


Aidin Zolghadr
Indie Game Developer | ShotgunSurgeons
[image: LinkedIn]  <https://www.linkedin.com/in/aidinzolghadr> [image:
Skype:hdgam3r]  [image: Youtube]
<https://www.youtube.com/user/GarageGameGuy/> [image: Github]
<https://github.com/aidinzolghadr>[image: Twitter]
<https://twitter.com/AidinZolghadr>

**Comment by neilcsmith-net** [comment]
It's up to you.  They're both "official" in the sense that they're both based on the same OpenJDK code and have passed the official TCKs.  There are some subtle differences, but I prefer the better license (and an installer that doesn't try to install other stuff) - Oracle JDK 8 should work just as well.  The key thing is to end up with one 64-bit Java 8 JDK until Praxis LIVE gets a bundled JDK.

I'd forgotten the client/server thing - I'm not at the machine I can check for sure, but assume client as it's an installer (*.msi)?

**Comment by neilcsmith-net** [comment]
Assuming you got sorted with this?  I'm going to close.  Please reopen if need be.  Thanks.
